# Generated by Django 4.2.30 on 2026-08-10 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_end_date_project_start_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at'], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
    ]
